language: php

php:
    - 5.4

before_script:
  - composer self-update
  - composer install --dev
  - bash tests/bin/travis_jackrabbit.sh

script: 
  - phpunit --coverage-text
  - php vendor/behat/behat/bin/behat --format=failed
  - php vendor/bin/phpspec run
